####2.2) Data Dictionary (10 pts)
## 3) Data Preparation (20 pts)
## 4) Shot Charts (20 pts)
####4.1) Shot charts of each player (10 pts)
####4.2) Facetted Shot Chart (10 pts)
## 5) Summary Tables (20 pts)
####5.1) Total Shots by Player (10 pts)
####5.2) Effective Shooting Percentage (10 pts)
## 6) Shooting Distance (20 pts)
####6.1) dplyr table (10 pts)
####6.2) ggplot (10 pts)
## 7) Total number of shots by minute of occurrence (10 pts)
